"""book search_text

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 16:21:20.111890

"""
from typing import Sequence, Union

import re
import unicodedata

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# کپی ثابت از app.core.text.search_key در زمان نوشتن این migration.
# عمداً import نمی‌شود تا تغییرات آینده‌ی کد، نتیجه‌ی این migration را عوض نکند.
_LETTERS = str.maketrans({"ي": "ی", "ى": "ی", "ك": "ک"})
_SEARCH_ONLY = str.maketrans({
    "آ": "ا", "أ": "ا", "إ": "ا", "ٱ": "ا", "ۀ": "ه", "ة": "ه", "ؤ": "و",
    **{chr(0x06F0 + i): str(i) for i in range(10)},
    **{chr(0x0660 + i): str(i) for i in range(10)},
})
_MARKS = re.compile(r"[\u064B-\u065F\u0670\u06D6-\u06ED\u0640]")


def _search_key(text: str) -> str:
    text = _MARKS.sub("", unicodedata.normalize("NFKC", text)).translate(_LETTERS)
    return re.sub(r"[\W_]+", "", text.translate(_SEARCH_ONLY).lower())


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('books', sa.Column('search_text', sa.String(length=500), server_default='', nullable=False))

    # پر کردن کلید جستجو برای کتاب‌های موجود
    conn = op.get_bind()
    books = sa.table("books", sa.column("id"), sa.column("title"), sa.column("author"), sa.column("search_text"))
    for row in conn.execute(sa.select(books.c.id, books.c.title, books.c.author)).all():
        conn.execute(
            books.update().where(books.c.id == row.id).values(search_text=_search_key(f"{row.title} {row.author}"))
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'search_text')
    # ### end Alembic commands ###
